server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8443
spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Qwerty@1
    url: jdbc:sqlserver://localhost:1433;databaseName=testdb
    username: manojdev
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
        generate_statistics: false
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
  cache:
    jcache:
      config: classpath:ehcache.xml
  flyway:
    url: jdbc:sqlserver://localhost:1433;databaseName=testdb
    schemas: dbo
    user: "manojdev"
    password: "Qwerty@1"
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/repeatableScript

management:
  endpoints:
    web:
      exposure:
        include: '*'
